# Atelier Préparation de Données Tabulaires

## Contexte
Une entreprise exploite plusieurs bâtiments intelligents équipés de capteurs IoT. Chaque capteur
collecte régulièrement des informations sur la température, l'humidité, la qualité de l'air, la
consommation énergétique, le nombre de personnes présentes, le type de bâtiment, le mode de
fonctionnement et l'état du système de climatisation.
Les données collectées sont destinées à alimenter ultérieurement un modèle de Machine Learning
capable de prédire la consommation énergétique ou de détecter les situations anormales.
Cependant, les données brutes présentent volontairement différents problèmes : valeurs
manquantes, doublons, valeurs aberrantes, types incorrects, valeurs incohérentes, variables
catégorielles, catégories rares, déséquilibre des classes et échelles différentes entre variables.
L'objectif de l'atelier est donc de transformer le fichier brut en un jeu de données propre et prêt
pour le Machine Learning.

## Objectifs pédagogiques
À la fin de l'atelier, l'apprenant doit être capable de :
1) explorer un jeu de données tabulaire ;
2) identifier les différents types de variables ;
3) détecter les problèmes de qualité ;
4) analyser les valeurs manquantes ;
5) détecter et traiter les doublons ;
6) identifier les valeurs aberrantes ;
7) détecter les incohérences ;
8) analyser le déséquilibre des classes ;
9) choisir une stratégie d'encodage adaptée ;
10) appliquer différents encodages catégoriels ;
11) normaliser et standardiser les variables numériques ;
12) éviter la fuite de données ;
13) construire un pipeline de preprocessing avec Scikit-learn ;
14) produire un dataset final exploitable par un algorithme de Machine Learning.

### Partie 1 – Explorer les données

### 1) Charger les données CSV

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sine/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/sine/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 5.6 MB/s eta 0:00:00a 0:00:01
Downloading numpy-2.5.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 5.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

df = pd.read_csv("../data/smart_building_raw.csv")

### 2) Afficher les premières lignes du dataset

In [4]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

### 3) Afficher les dernières lignes du dataset

In [5]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

### 4) Combien d'observations contient le dataset

In [7]:
df.shape[0]

507

### 5) Combien de variables possède le dataset

In [8]:
df.shape[1]

14

### 6) Identifier les variables numériques

In [9]:
df.select_dtypes(include="number").columns

Index(['id_mesure', 'temperature', 'humidite', 'co2', 'occupation',
       'consommation_kwh'],
      dtype='str')

### 7) Identifier les variables catégorielles

In [10]:
df.select_dtypes(include="object").columns

/tmp/ipykernel_6394/1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['date', 'batiment', 'type_batiment', 'zone', 'mode_climatisation',
       'etat_systeme', 'jour_semaine', 'alerte'],
      dtype='str')

### 8) Identifier les dates

In [12]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["date"].head()

0   2025-02-13 06:00:00
1   2025-03-10 12:00:00
2   2025-05-04 00:00:00
3   2025-01-19 00:00:00
4   2025-04-24 06:00:00
Name: date, dtype: datetime64[us]

### 9) Identifier les identifiants

In [13]:
df["id_mesure"]

0      1174
1      1275
2      1493
3      1073
4      1454
       ...
502    1107
503    1271
504    1349
505    1436
506    1103
Name: id_mesure, Length: 507, dtype: int64

### 10) Déterminer les statistiques : moyenne, médiane, minimum, maximum, écart-type et quartiles

In [14]:
df.describe()

,id_mesure,date,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,502,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,2025-03-04 13:26:03.346613,24.154141,57.864113,844.150000,44.850299,169.069323
min,1001.000000,2025-01-01 00:00:00,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,2025-02-01 01:30:00,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,2025-03-04 21:00:00,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,2025-04-04 22:30:00,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,2025-05-05 18:00:00,96.000000,160.000000,6000.000000,116.000000,336.200000
std,144.782769,NaN,7.418465,16.026336,582.181386,24.949139,53.164294

### 11) Y a-t-il des variables potentiellement problématiques ?

L'exploration révèle plusieurs variables potentiellement problématiques. Sur le plan des types, id_mesure est stocké comme une variable numérique alors qu'il s'agit en réalité d'un identifiant, sans signification statistique. La colonne date, initialement de type texte, a nécessité une conversion explicite en datetime, et certaines valeurs n'ont pas pu être interprétées. Sur le plan des valeurs, humidite (exprimée en pourcentage) présente potentiellement des valeurs hors de la plage logique [0, 100], tandis que temperature et consommation_kwh affichent des écarts importants entre leurs valeurs minimales et maximales, suggérant la présence de valeurs aberrantes ou de mesures physiquement incohérentes (température extrême, consommation négative). Enfin, les variables catégorielles (type_batiment, mode_climatisation, etat_systeme, jour_semaine, alerte) doivent être examinées pour détecter d'éventuelles catégories mal orthographiées, des espaces parasites, ou une casse incohérente (majuscules/minuscules mélangées), ainsi qu'un possible déséquilibre de classes, en particulier sur la variable cible alerte.